index.html
subDirectory/ricoPage.html

My page is annoying...by just looking at it. Decided to try to go old school styling with it.

added rico page and modified the index page to link to it

---

index.html
subDirectory/allanPage.html

Added a stupidly pointless user journey - driven by a tale of a lost button. it's annoying. it's heartbreaking. It's the 2017's big love story. It's a HTML page.

Added my page

---

index.html
subDirectory/wtsamplerPage.html

Here is my example of a really annoying directory page - thanks for letting me contribute!

This is my ReallyAnnoyingDirectory Page

---

subDirectory/allanPage.html

Ok, I think I did everything right. Fixed issue 10, button misspelled in allanPage.html

fixed issue #10, changing the word buttton to button

---

index.html
subDirectory/amoutonbrady.html

Had quite a lot of fun creating this little thing. Been willing to play with animations for a long time.
Therefore, here's whats annoying/funny about it:
* the odd colors which are all native to CSS (beside the box-shadow one)
* the annoying animations
* the randomness of the popups
* the overused emojis? :)
I used some ES6 stuff because I was lazy and the anime.js library. Things might break in older browsers.
I tried comment as much the scripts as possible (which is where the whole magic happen anyway).
Hope you like it!
PS: sorry for the reformatting of the front page, prettier can be annoying sometimes

Added my page Amoutonbrady + link on the front page

---

subDirectory/allanPage.html
subDirectory/ljp1203Page.html

- fixed small spelling mistakes
- changed some text to flow better with the way other sentences were written
- fixed grammar errors

Fixed spelling/grammar mistakes on Allan's page and added link back to Repo on mine

---

index.html
subDirectory/ajamesmPage.html

My page has a rainbow background gradient with lots of clashing colors. It utilizes JS to transform several text elements and an image. It has little information and no functionality. I aimed for an /r/CrappyDesign type feel (minus the comic sans)

ajamesm PR

---

index.html
styles/default.css

Added a dropdown UI in the top left corner.

Dropdown UI added

---

index.html
scripts/script.js
styles/default.css
styles/finchMFG.css

- Style Sheet Compact Dropdown Starts off closed but when clicked extends out #21 done.

dropdown slide out done

---

index.html
scripts/script.js

Add CSS switcher

---

subDirectory/TEMPLATE.html

A fix for the incorrect url, regarding issue #36.

Fixed incorrect url (issue #36)

---

subDirectory/SirDrapplePage.html
subDirectory/ajamesmPage.html
subDirectory/allanPage.html
subDirectory/amoutonbrady.html
subDirectory/finchMFGPage.html
subDirectory/ljp1203Page.html
subDirectory/ricoPage.html
subDirectory/torPage.html
subDirectory/wtsamplerPage.html

Fixed outdated urls on all subdirectories

---

styles/default.css

there was div overlay <a> with z-index 100
simple solution: add z-index 101 to <a>

allow use link to GitHub

---

index.html
subDirectory/thomas-booker.html

Hi there
Created thomas-booker.html annoying page
Added to directory
Thank you :)

Created annoying page, added to directory

---

index.html
styles/default.css

Added the transition to the CSS file
The 'visible style change on page load' fixed by loading CSS before JS

Add transition effect on load

---

index.html
subDirectory/ntno.html

hello!  i have created a new annoying page.  
reasons it is annoying:
- times new roman
- random muddy colors
- navbar background blends into the rest of the page background
- the links in the navbar drop down all result in 404.
--> except one!!! which is selected at random.

new page - ntno

---

index.html
subDirectory/kellymarjorie.html

This page is ugly! Button back to directory moves around the page 5 times on mouseover and background color changes, before reverting to original settings.

Added kellymarjorie.html

---

index.html

Added link to Index.html to point to jawasawa... Thanks and sorry whoops!

Added a link to jawasawa.html in index

---

index.html
subDirectory/atropos148.html

Hello everyone atropos148 here, just adding my page, ill keep working on it to make it even better

atropos148 page v1

---

index.html
subDirectory/binarydigit.html

all hail binarydigit's page

---

subDirectory/mongjong86.html

Adding my page

---

subDirectory/devchamploo.html

I added my pade into the sub directory. It is an html file with included styles in the subdirectory folder.

Added my page - devchamploo.html

---

subDirectory/faster_return.html

i have made this webpage myself

a new webpage
